apiVersion: v1
kind: Pod
metadata:
  name: grafana-seed
spec:
  containers:
  - image: alpine:latest
    name: grafana-seed
    command:
      - "/srv/grafana/seed.sh"
    volumeMounts:
    - mountPath: /srv/grafana
      name: git-volume
#     env:
#     	- name: PROM_URL
#         valueFrom:
#           configMapKeyRef:
#           	name: grafana-seed-config
#           	key: prom-url
#     	- name: DATASOURCE_DIR
#         valueFrom:
#           configMapKeyRef:
#           	name: grafana-seed-config
#           	key: datasource-dir
#     	- name: DASHBOARD_DIR
#         valueFrom:
#           configMapKeyRef:
#           	name: grafana-seed-config
#           	key: dashboard-dir
  restartPolicy: Never
  volumes:
  - name: git-volume
    gitRepo:
      repository: "https://github.com/rothgar/grafana-seed.git"
      revision: "demov1"
